# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
title: Gandhi's Musings
email: n.nyoman.gandhi@gandhi.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! This is a blog about software engineering, 
  lessons learned, and slice of life i've accumulated during my journey to become
  an IT craftsman.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Gandhi_NN
github_username:  GandhiNN
domain: gandhinn.github.io
url: https://gandhinn.github.io
minimal_mistakes_skin: default
search: true
show_excerpts: true

# Build settings
# theme: minima
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag
  
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Include
include:
  - _pages

# List of keywords
category-list: [Code, Unix, Linux, Rust, Python, Go]

author:
  name   : "Ngakan Gandhi"
  avatar : "/assets/images/foto.jpg"
  bio    : >
   IT Solution Expert @ Philip Morris International. 
   Speaks in Command-Line Interface. 
   The opinions shared here do not represent the views of the employers.
  location: "Jakarta, Indonesia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://gandhinn.github.io"
    - label: "Twitter/X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/gandhi_nn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GandhiNN"

footer:
  links:
    - label: "Twitter/X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/gandhi_nn"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GandhiNN"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# use utterances for comments
repository: "GandhiNN/gandhinn.github.io"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" 
    issue-term: "pathname"
    label: "comment"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Compress
compress_html:
  clippings: all
  ignore:
    envs: development # disable compression in dev environment


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - backup/

# Remove the RSS icon
atom_feed:
  hide: true